services:
  nginx:
    build: ./requirements/nginx
    image: nginx
    ports:
      - "443:443"
    volumes:
      - wp_data:/var/www/html
    depends_on:
      - wordpress
    networks:
      - backend
    restart: always

  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    volumes:
      - wp_data:/var/www/html
    expose:
      - "9000"
    env_file:
      - .env
    depends_on:
      - mariadb
    networks:
      - backend
    restart: always

  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
    expose:
      - "3306"
    networks:
      - backend
    restart: always

  adminer:
    build: ./requirements/bonus/adminer
    image: adminer
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "9090:9090"
    networks:
      - backend
    restart: always

  cadviser:
    build: ./requirements/bonus/cadviser
    image: cadviser
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    ports:
      - "8080:8080"
    networks:
      - backend
    env_file:
      - .env
    restart: always

networks:
  backend:
    driver: bridge

volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/yasseroo/data/mariadb
  wp_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/yasseroo/data/wordpress
