services:
  nginx:
    build: ./requirements/nginx
    ports:
      - "443:443"
    volumes:
      - ./requirements/wordpress:/var/www/html
    depends_on:
      - wordpress
    networks:
      - backend

  wordpress:
    build: ./requirements/wordpress
    volumes:
      - ./requirements/wordpress:/var/www/html
    expose:
      - "9000"
    env_file:
      - .env
    depends_on:
      - mariadb
    networks:
      - backend
    restart: unless-stopped

  mariadb:
    build: ./requirements/mariadb
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
    expose:
      - "3306"
    networks:
      - backend
    restart: unless-stopped

networks:
  backend:
    driver: bridge

volumes:
  db_data:
