services:
  nginx:
    build: ./requirements/nginx
    ports:
      - "443:443"
    volumes:
      - ./requirements/wordpress:/var/www/html
    depends_on:
      - wordpress
    networks:
      - backend

  wordpress:
    build: ./requirements/wordpress
    volumes:
      - ./requirements/wordpress:/var/www/html
    expose:
      - "9000"
    networks:
      - backend
    restart: unless-stopped

networks:
  backend:
    driver: bridge
