services:
  nginx:
    build: ./requirements/nginx
    image: nginx
    ports:
      - "443:443"
    volumes:
      - wp_data:/var/www/html
    depends_on:
      - wordpress
    networks:
      - backend

  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    volumes:
      - wp_data:/var/www/html
    expose:
      - "9000"
    env_file:
      - .env
    depends_on:
      - mariadb
    networks:
      - backend
    restart: unless-stopped

  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
    expose:
      - "3306"
    networks:
      - backend
    restart: unless-stopped

networks:
  backend:
    driver: bridge

volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/yasseroo/data/mariadb
  wp_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/yasseroo/data/wordpress
